#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QDebug>
#include <QTemporaryDir>
#include <QStringList>
#include <QTextStream>

#include "compiler/DSLCompilerInterface.h"

namespace {
bool writeTextFile(const QString& filePath, const QString& text)
{
    QFile file(filePath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate)) {
        qCritical() << "Failed to write DSL fixture:" << filePath;
        return false;
    }
    QTextStream out(&file);
    out << text;
    return true;
}

QString readTextFile(const QString& filePath)
{
    QFile file(filePath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return QString();
    }
    return QString::fromUtf8(file.readAll());
}

QString diagnostics(const CompileResult& result)
{
    return result.errors.join(QLatin1Char('\n'))
           + QLatin1Char('\n') + result.stdErr
           + QLatin1Char('\n') + result.stdOut;
}

bool runtimeUnavailable(const QString& text)
{
    static const QStringList markers{
        QStringLiteral("No suitable Python interpreter found"),
        QStringLiteral("Missing required module 'antlr4-python3-runtime'"),
        QStringLiteral("No module named 'antlr4'"),
        QStringLiteral("ModuleNotFoundError: No module named 'antlr4'"),
        QStringLiteral("Compiler entry script not found"),
        QStringLiteral("Unable to create process"),
        QStringLiteral("Failed to start")
    };
    for (const QString& marker : markers) {
        if (text.contains(marker, Qt::CaseInsensitive)) {
            return true;
        }
    }
    return false;
}

bool hasArtifact(const CompileResult& result,
                 const QString& type,
                 const QString& format,
                 const QString& path)
{
    for (const CompileArtifact& artifact : result.artifacts) {
        if (artifact.type == type
                && artifact.format == format
                && QFileInfo::exists(artifact.path)
                && artifact.path == path
                && !artifact.checksum.isEmpty()) {
            return true;
        }
    }
    return false;
}

bool assertSuccessfulPublication(const CompileResult& result,
                                 const QString& outputDir,
                                 const QString& sourcePath)
{
    const QString codePath = QDir(outputDir).filePath(QStringLiteral("%1.code")
                                                        .arg(QFileInfo(sourcePath).completeBaseName()));
    const QString listPath = QDir(outputDir).filePath(QStringLiteral("%1.list")
                                                        .arg(QFileInfo(sourcePath).completeBaseName()));
    const QString typPath = QDir(outputDir).filePath(QStringLiteral("%1.typ")
                                                       .arg(QFileInfo(sourcePath).completeBaseName()));
    const QString repPath = QDir(outputDir).filePath(QStringLiteral("%1.rep")
                                                       .arg(QFileInfo(sourcePath).completeBaseName()));

    if (!result.success || !result.errors.isEmpty() || !QFileInfo::exists(codePath)) {
        qCritical() << "Successful DSL fixture was not compiled:" << diagnostics(result);
        return false;
    }
    if (!hasArtifact(result, QStringLiteral("download"), QStringLiteral("dsl_custom"), codePath)
            || !hasArtifact(result, QStringLiteral("parameter_initials"),
                            QStringLiteral("lh_parameter_initials"), listPath)
            || !hasArtifact(result, QStringLiteral("parameter_layout"),
                            QStringLiteral("lh_parameter_layout"), typPath)
            || !hasArtifact(result, QStringLiteral("compile_report"),
                            QStringLiteral("lh_compile_report"), repPath)) {
        qCritical() << "Successful DSL fixture did not publish the expected artifacts."
                    << result.artifacts.size();
        return false;
    }
    const QString codeText = readTextFile(codePath);
    if (!codeText.startsWith(QStringLiteral("// Generated by LH compiler integration"))
            || !codeText.contains(QStringLiteral("// Format: .lh -> .code"))) {
        qCritical() << "Successful DSL output is missing the integration metadata header.";
        return false;
    }
    return true;
}

bool assertFailedPublication(const CompileResult& result,
                             const QString& outputDir,
                             const QString& sourcePath)
{
    const QString codePath = QDir(outputDir).filePath(QStringLiteral("%1.code")
                                                        .arg(QFileInfo(sourcePath).completeBaseName()));
    if (result.success || diagnostics(result).trimmed().isEmpty()
            || QFileInfo::exists(codePath)) {
        qCritical() << "Invalid DSL fixture did not fail without publishing .code:"
                    << diagnostics(result);
        return false;
    }
    for (const CompileArtifact& artifact : result.artifacts) {
        if (artifact.type == QStringLiteral("download")) {
            qCritical() << "Failed DSL fixture published a download artifact:" << artifact.path;
            return false;
        }
    }
    return true;
}
} // namespace

int main(int argc, char* argv[])
{
    QCoreApplication app(argc, argv);

    QTemporaryDir temporaryRoot;
    if (!temporaryRoot.isValid()) {
        qCritical() << "Failed to create temporary DSL semantics test root."
                    << temporaryRoot.errorString();
        return 1;
    }
    const QString runtimeRoot = temporaryRoot.path();
    const QString sourceDir = QDir(runtimeRoot).filePath(QStringLiteral("sources"));
    const QString outputDir = QDir(runtimeRoot).filePath(QStringLiteral("outputs"));
    QDir().mkpath(sourceDir);
    QDir().mkpath(outputDir);

    DSLCompilerInterface compiler;
    QString componentStdout;
    QString componentStderr;
    if (!compiler.listComponents(&componentStdout, &componentStderr)) {
        const QString componentDiagnostics = componentStdout + QLatin1Char('\n') + componentStderr;
        if (runtimeUnavailable(componentDiagnostics)) {
            qWarning() << "DSL compiler semantics test skipped: Python/ANTLR compiler runtime is unavailable."
                       << componentDiagnostics;
            return 77;
        }
        qCritical() << "DSL compiler component discovery failed:" << componentDiagnostics;
        return 1;
    }

    const QString basicSourcePath = QDir(sourceDir).filePath(QStringLiteral("basic.lh"));
    const QString basicOutputDir = QDir(outputDir).filePath(QStringLiteral("basic"));
    if (!writeTextFile(basicSourcePath,
                       QStringLiteral(
                           "PROGRAM Basic\n"
                           "VAR\n"
                           "    flag : BOOL;\n"
                           "END_VAR\n"
                           "flag := TRUE;\n"
                           "END_PROGRAM\n"))) {
        return 1;
    }
    const CompileResult basicResult = compiler.compileDslFileWithResult(
        basicSourcePath, basicOutputDir, QStringLiteral("basic_semantics"));
    if (runtimeUnavailable(diagnostics(basicResult))) {
        qWarning() << "DSL compiler semantics test skipped during compile:" << diagnostics(basicResult);
        return 77;
    }
    if (!assertSuccessfulPublication(basicResult, basicOutputDir, basicSourcePath)) {
        return 1;
    }

    const QString legacySourcePath = QDir(sourceDir).filePath(QStringLiteral("legacy_block.lh"));
    const QString legacyOutputDir = QDir(outputDir).filePath(QStringLiteral("legacy_block"));
    if (!writeTextFile(legacySourcePath,
                       QStringLiteral(
                           "drv_do_1 = _DrvDO(\n"
                           "    OutputWord = 0,\n"
                           "    Port = 0,\n"
                           "    Mask = 255,\n"
                           "    Action = 1\n"
                           ");\n"))) {
        return 1;
    }
    const CompileResult legacyResult = compiler.compileDslFileWithResult(
        legacySourcePath, legacyOutputDir, QStringLiteral("legacy_block_semantics"));
    if (runtimeUnavailable(diagnostics(legacyResult))) {
        qWarning() << "DSL compiler semantics test skipped during legacy compile:"
                   << diagnostics(legacyResult);
        return 77;
    }
    if (!assertSuccessfulPublication(legacyResult, legacyOutputDir, legacySourcePath)) {
        return 1;
    }
    const QString stagedLegacyPath = QDir(legacyOutputDir).filePath(
        QStringLiteral(".compiler_staging/legacy_block.lh"));
    const QString stagedLegacy = readTextFile(stagedLegacyPath);
    if (!stagedLegacy.contains(QStringLiteral("PROGRAM legacy_block"))
            || !stagedLegacy.contains(QStringLiteral("drv_do_1 : DrvDO;"))
            || !stagedLegacy.contains(QStringLiteral("drv_do_1("))
            || stagedLegacy.contains(QStringLiteral("= _DrvDO("))) {
        qCritical() << "Legacy function-block DSL normalization contract failed."
                    << stagedLegacy;
        return 1;
    }

    const QString syntaxSourcePath = QDir(sourceDir).filePath(QStringLiteral("syntax_error.lh"));
    const QString syntaxOutputDir = QDir(outputDir).filePath(QStringLiteral("syntax_error"));
    if (!writeTextFile(syntaxSourcePath,
                       QStringLiteral(
                           "PROGRAM SyntaxError\n"
                           "VAR\n"
                           "    flag : BOOL;\n"
                           "END_VAR\n"
                           "flag := ;\n"
                           "END_PROGRAM\n"))) {
        return 1;
    }
    const CompileResult syntaxResult = compiler.compileDslFileWithResult(
        syntaxSourcePath, syntaxOutputDir, QStringLiteral("syntax_error_semantics"));
    if (runtimeUnavailable(diagnostics(syntaxResult))) {
        qWarning() << "DSL compiler semantics test skipped during syntax check:"
                   << diagnostics(syntaxResult);
        return 77;
    }
    if (!assertFailedPublication(syntaxResult, syntaxOutputDir, syntaxSourcePath)) {
        return 1;
    }

    const QString unknownSourcePath = QDir(sourceDir).filePath(QStringLiteral("unknown_block.lh"));
    const QString unknownOutputDir = QDir(outputDir).filePath(QStringLiteral("unknown_block"));
    if (!writeTextFile(unknownSourcePath,
                       QStringLiteral(
                           "unknown_1 = _DefinitelyUnknown(\n"
                           "    Value = 1\n"
                           ");\n"))) {
        return 1;
    }
    const CompileResult unknownResult = compiler.compileDslFileWithResult(
        unknownSourcePath, unknownOutputDir, QStringLiteral("unknown_block_semantics"));
    if (runtimeUnavailable(diagnostics(unknownResult))) {
        qWarning() << "DSL compiler semantics test skipped during unknown-block check:"
                   << diagnostics(unknownResult);
        return 77;
    }
    if (!assertFailedPublication(unknownResult, unknownOutputDir, unknownSourcePath)) {
        return 1;
    }

    qInfo() << "DSL compiler semantics test passed.";
    return 0;
}
