#include "DSLCompilerInterface.h"
#include "DSLCompilerInternal.h"

#include <QCryptographicHash>
#include <QDateTime>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QSaveFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QProcess>
#include <QRegularExpression>
#include <QDebug>
#include <QUuid>
#include <algorithm>
#include "TextEncoding.h"

namespace DSLCompilerInternal {

QString defaultOutputFileForSource(const QString& sourceFile, const QString& outputDir)
{
    if (QFileInfo(QDir(outputDir).absolutePath()).dir().dirName()
            == QStringLiteral("generations")) {
        return projectOutputFile(outputDir);
    }
    const QFileInfo sourceInfo(sourceFile);
    return QDir(outputDir).absoluteFilePath(sourceInfo.completeBaseName() + QStringLiteral(".code"));
}

QString projectOutputFile(const QString& outputDir)
{
    return QDir(outputDir).absoluteFilePath(QStringLiteral("main.code"));
}

QString outputSidecarFileForSource(const QString& sourceFile,
                                   const QString& outputDir,
                                   const QString& suffix)
{
    const QFileInfo sourceInfo(sourceFile);
    const QString baseName = QFileInfo(QDir(outputDir).absolutePath()).dir().dirName()
            == QStringLiteral("generations")
            ? QStringLiteral("main")
            : sourceInfo.completeBaseName();
    return QDir(outputDir).absoluteFilePath(baseName + suffix);
}

QStringList buildCompilerProcessArgs(const QString& entryScript,
                                     const QString& compilerInputFile,
                                     const QString& outputFile)
{
    return QStringList()
            << entryScript
            << QDir::toNativeSeparators(compilerInputFile)
            << QStringLiteral("-o")
            << QDir::toNativeSeparators(outputFile)
            << QStringLiteral("-v");
}

bool prependCodeMetadataHeader(const QString& outputFile,
                               const QString& sourceFile,
                               const QString& projectName,
                               const QString& compilerInputFile,
                               QString* errorMessage)
{
    QFile file(outputFile);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        if (errorMessage) {
            *errorMessage = QStringLiteral("Failed to read generated .code file: %1").arg(outputFile);
        }
        return false;
    }
    const QByteArray body = file.readAll();
    file.close();

    const QFileInfo sourceInfo(sourceFile);
    const QFileInfo outputInfo(outputFile);
    const QFileInfo compilerInputInfo(compilerInputFile);
    QStringList header;
    header << QStringLiteral("// Generated by LH compiler integration")
           << QStringLiteral("// GeneratedAt: %1").arg(QDateTime::currentDateTime().toString(Qt::ISODate))
           << QStringLiteral("// Project: %1").arg(projectName.isEmpty() ? QStringLiteral("-") : projectName)
           << QStringLiteral("// Source: %1").arg(QDir::toNativeSeparators(sourceInfo.fileName()))
           << QStringLiteral("// CompilerInput: %1").arg(QDir::toNativeSeparators(compilerInputInfo.fileName()))
           << QStringLiteral("// Output: %1").arg(QDir::toNativeSeparators(outputInfo.fileName()))
           << QStringLiteral("// Format: .lh -> .code")
           << QString();

    QSaveFile atomicFile(outputFile);
    if (!atomicFile.open(QIODevice::WriteOnly | QIODevice::Text)) {
        if (errorMessage) {
            *errorMessage = QStringLiteral("Failed to write generated .code metadata header: %1").arg(outputFile);
        }
        return false;
    }
    const QByteArray output = header.join(QLatin1Char('\n')).toUtf8() + body;
    if (atomicFile.write(output) != output.size() || !atomicFile.commit()) {
        if (errorMessage) {
            *errorMessage = QStringLiteral("Failed to commit generated .code metadata header: %1")
                    .arg(outputFile);
        }
        return false;
    }
    return QFileInfo::exists(outputFile);
}

QString sha256ForFile(const QString& filePath)
{
    QFile file(filePath);
    if (!file.open(QIODevice::ReadOnly)) {
        return QString();
    }
    QCryptographicHash hash(QCryptographicHash::Sha256);
    hash.addData(&file);
    return QString::fromLatin1(hash.result().toHex());
}

QString runDslCompilerProcess(const QString& python,
                              const QString& entryScript,
                              const QString& compilerInputFile,
                              const QString& outputFile,
                              const QString& workDir,
                              QString* compilerStdout,
                              QString* compilerStderr)
{
    const QStringList args = buildCompilerProcessArgs(entryScript, compilerInputFile, outputFile);

    QProcess proc;
    proc.setProgram(python);
    proc.setArguments(args);
    proc.setWorkingDirectory(workDir);

    qInfo() << "[DSLCompilerInterface] Running:" << python << args
            << "cwd =" << workDir;

    proc.start();
    if (!proc.waitForFinished(120 * 1000)) {
        proc.kill();
        if (compilerStderr) {
            *compilerStderr = QStringLiteral("DSL compile process timeout.");
        }
        qWarning() << "[DSLCompilerInterface] compile process timeout.";
        return QStringLiteral("timeout");
    }

    const QString stdOut =
            TextEncoding::decodeUtf8WithLocalFallback(proc.readAllStandardOutput());
    const QString stdErr =
            TextEncoding::decodeUtf8WithLocalFallback(proc.readAllStandardError());

    if (compilerStdout) {
        *compilerStdout = stdOut;
    }
    if (compilerStderr) {
        *compilerStderr = stdErr;
    }

    if (proc.exitStatus() == QProcess::NormalExit
            && proc.exitCode() == 0
            && QFileInfo::exists(outputFile)) {
        return QString();
    }

    return QStringLiteral("exitCode=%1 outputFile=%2")
            .arg(proc.exitCode())
            .arg(outputFile);
}

namespace {

bool pathWithinRoot(const QString& root, const QString& path)
{
    const QString relative = QDir(root).relativeFilePath(path);
    return relative != QStringLiteral("..")
            && !relative.startsWith(QStringLiteral("../"))
            && !relative.startsWith(QStringLiteral("..\\"))
            && !QDir::isAbsolutePath(relative);
}

bool hasParentTraversal(const QString& path)
{
    const QStringList parts = QDir::fromNativeSeparators(path).split(QLatin1Char('/'), Qt::SkipEmptyParts);
    return std::any_of(parts.constBegin(), parts.constEnd(), [](const QString& part) {
        return part == QStringLiteral("..");
    });
}

} // namespace

QString projectRelativePath(const QString& projectPath, const QString& absolutePath)
{
    return QDir(projectPath).relativeFilePath(QFileInfo(absolutePath).absoluteFilePath());
}

QString profileSourcePath(const QString& projectPath, const ProjectRuntimeConfig& config)
{
    QString configured;
    const QStringList keys = {
        QStringLiteral("downloadProfileSourcePath"),
        QStringLiteral("profileSourcePath"),
        QStringLiteral("sourceProfilePath"),
        QStringLiteral("downloadProfilePath"),
        QStringLiteral("profileJsonPath"),
        QStringLiteral("profilePath")
    };
    for (const QString& key : keys) {
        configured = config.downloadArtifact.metadata.value(key).toString().trimmed();
        const QString normalized = QDir::fromNativeSeparators(configured);
        if ((normalized.startsWith(QStringLiteral("generations/"))
             || normalized.contains(QStringLiteral("/generations/")))
                && normalized.endsWith(QStringLiteral("/download_profile.json"))) {
            configured.clear();
            continue;
        }
        if (!configured.isEmpty())
            break;
    }
    if (configured.isEmpty())
        return QString();
    if (QFileInfo(configured).isRelative())
        return QDir(projectPath).absoluteFilePath(configured);
    return QFileInfo(configured).absoluteFilePath();
}

namespace {

bool validateProfileJson(const QByteArray& bytes, QString* errorMessage)
{
    QJsonParseError parseError;
    const QJsonDocument document = QJsonDocument::fromJson(bytes, &parseError);
    if (parseError.error != QJsonParseError::NoError || !document.isObject()) {
        if (errorMessage) {
            *errorMessage = QStringLiteral("下载 Profile 不是有效 JSON 对象：%1")
                    .arg(parseError.error == QJsonParseError::NoError
                             ? QStringLiteral("根节点必须是对象")
                             : parseError.errorString());
        }
        return false;
    }

    const QJsonObject object = document.object();
    const QJsonValue slaveId = object.value(QStringLiteral("slaveId"));
    if (!slaveId.isUndefined() && (!slaveId.isDouble() || slaveId.toInt() < 1 || slaveId.toInt() > 63)) {
        if (errorMessage)
            *errorMessage = QStringLiteral("下载 Profile 的 slaveId 必须为 1..63。");
        return false;
    }
    const QJsonValue steps = object.value(QStringLiteral("steps"));
    if (!steps.isArray() || steps.toArray().isEmpty()) {
        if (errorMessage)
            *errorMessage = QStringLiteral("下载 Profile 必须包含非空 steps 数组。");
        return false;
    }
    bool hasSendChunk = false;
    for (const QJsonValue& step : steps.toArray()) {
        const QString type = step.isObject()
                ? step.toObject().value(QStringLiteral("type")).toString().trimmed().toLower()
                : QString();
        if (type == QStringLiteral("sendchunk"))
            hasSendChunk = true;
        if (!step.isObject()
                || !step.toObject().value(QStringLiteral("params")).isObject()
                || (type != QStringLiteral("enter")
                && type != QStringLiteral("sendchunk")
                && type != QStringLiteral("poll")
                && type != QStringLiteral("finalize")
                && type != QStringLiteral("queryresult"))) {
            if (errorMessage)
                *errorMessage = QStringLiteral("下载 Profile 含有未知或缺失的 step.type。");
            return false;
        }
    }
    if (!hasSendChunk) {
        if (errorMessage)
            *errorMessage = QStringLiteral("下载 Profile 至少需要一个 sendChunk step。");
        return false;
    }
    return true;
}

bool copyFileAtomically(const QString& sourcePath, const QString& destinationPath, QString* errorMessage)
{
    QFile source(sourcePath);
    if (!source.open(QIODevice::ReadOnly)) {
        if (errorMessage)
            *errorMessage = QStringLiteral("无法读取下载 Profile：%1").arg(sourcePath);
        return false;
    }
    const QByteArray bytes = source.readAll();
    if (source.error() != QFileDevice::NoError) {
        if (errorMessage)
            *errorMessage = QStringLiteral("读取下载 Profile 失败：%1").arg(sourcePath);
        return false;
    }

    QSaveFile destination(destinationPath);
    if (!destination.open(QIODevice::WriteOnly) || destination.write(bytes) != bytes.size()
            || !destination.commit()) {
        if (errorMessage)
            *errorMessage = QStringLiteral("无法原子发布下载 Profile：%1").arg(destinationPath);
        return false;
    }
    return QFileInfo::exists(destinationPath);
}

} // namespace

bool validateProjectScriptPath(const QString& projectPath,
                               const QString& path,
                               QString* errorMessage)
{
    const QString trimmed = path.trimmed();
    if (trimmed.isEmpty()) {
        if (errorMessage)
            *errorMessage = QStringLiteral("项目脚本路径不能为空。");
        return false;
    }
    if (QFileInfo(trimmed).isRelative() && hasParentTraversal(trimmed)) {
        if (errorMessage)
            *errorMessage = QStringLiteral("项目脚本路径禁止包含 '..'：%1").arg(path);
        return false;
    }

    const QString root = QFileInfo(projectPath).canonicalFilePath();
    const QString absolute = QFileInfo(QFileInfo(trimmed).isRelative()
                                           ? QDir(projectPath).absoluteFilePath(trimmed)
                                           : trimmed).absoluteFilePath();
    if (root.isEmpty() || !pathWithinRoot(root, absolute)) {
        if (errorMessage)
            *errorMessage = QStringLiteral("项目脚本路径越出项目根目录：%1").arg(path);
        return false;
    }

    const QFileInfo candidate(absolute);
    if (candidate.exists()) {
        const QString canonical = candidate.canonicalFilePath();
        if (canonical.isEmpty() || !pathWithinRoot(root, canonical)) {
            if (errorMessage)
                *errorMessage = QStringLiteral("项目脚本符号链接越出项目根目录：%1").arg(path);
            return false;
        }
    } else {
        QDir parent = candidate.dir();
        while (!parent.exists()) {
            const QString currentPath = parent.absolutePath();
            const QDir nextParent = QFileInfo(currentPath).dir();
            if (nextParent.absolutePath() == currentPath)
                break;
            parent = nextParent;
        }
        const QString canonicalParent = parent.canonicalPath();
        if (canonicalParent.isEmpty() || !pathWithinRoot(root, canonicalParent)) {
            if (errorMessage)
                *errorMessage = QStringLiteral("项目脚本父目录越出项目根目录：%1").arg(path);
            return false;
        }
    }
    return true;
}

QString createProjectGeneration(const QString& projectPath,
                                const ProjectRuntimeConfig& config,
                                const QString& baseOutputDir,
                                QString* generationId,
                                QString* errorMessage)
{
    if (projectPath.trimmed().isEmpty() || baseOutputDir.trimmed().isEmpty()) {
        if (errorMessage)
            *errorMessage = QStringLiteral("项目发布目录不能为空。");
        return QString();
    }

    const QString root = QFileInfo(projectPath).canonicalFilePath();
    if (root.isEmpty()) {
        if (errorMessage)
            *errorMessage = QStringLiteral("项目根目录无法解析：%1").arg(projectPath);
        return QString();
    }

    const QString absoluteBaseOutputDir = QFileInfo(baseOutputDir).isRelative()
            ? QDir(root).absoluteFilePath(baseOutputDir)
            : QFileInfo(baseOutputDir).absoluteFilePath();
    QString outputPathError;
    if (!validateProjectScriptPath(root, absoluteBaseOutputDir, &outputPathError)) {
        if (errorMessage)
            *errorMessage = QStringLiteral("项目编译输出目录无效：%1").arg(outputPathError);
        return QString();
    }

    const QString profile = profileSourcePath(root, config);
    QString pathError;
    if (!validateProjectScriptPath(root, profile, &pathError)) {
        if (errorMessage)
            *errorMessage = profile.isEmpty()
                    ? QStringLiteral("未配置有效下载 Profile，已阻止正式发布。")
                    : pathError;
        return QString();
    }
    const QFileInfo profileInfo(QFileInfo(profile).absoluteFilePath());
    if (!profileInfo.exists() || !profileInfo.isFile() || !profileInfo.isReadable()) {
        if (errorMessage)
            *errorMessage = QStringLiteral("下载 Profile 不存在或不可读：%1").arg(profile);
        return QString();
    }

    QFile profileFile(profile);
    if (!profileFile.open(QIODevice::ReadOnly)) {
        if (errorMessage)
            *errorMessage = QStringLiteral("无法读取下载 Profile：%1").arg(profile);
        return QString();
    }
    const QByteArray profileBytes = profileFile.readAll();
    if (!validateProfileJson(profileBytes, errorMessage))
        return QString();

    const QString id = QUuid::createUuid().toString(QUuid::WithoutBraces);
    const QString generationDir = QDir(absoluteBaseOutputDir).absoluteFilePath(
            QStringLiteral("generations/%1").arg(id));
    if (!validateProjectScriptPath(root, generationDir, &outputPathError)) {
        if (errorMessage)
            *errorMessage = QStringLiteral("generation 输出目录无效：%1").arg(outputPathError);
        return QString();
    }
    if (!QDir().mkpath(generationDir)) {
        if (errorMessage)
            *errorMessage = QStringLiteral("无法创建编译 generation：%1").arg(generationDir);
        return QString();
    }

    const QString generationProfile = QDir(generationDir).filePath(QStringLiteral("download_profile.json"));
    if (!copyFileAtomically(profile, generationProfile, errorMessage))
        return QString();
    if (generationId)
        *generationId = id;
    return generationDir;
}

} // namespace DSLCompilerInternal

namespace {

QString generationIdForDirectory(const QString& outputDir)
{
    const QFileInfo outputInfo(outputDir);
    const QDir generationParent = outputInfo.dir();
    return generationParent.dirName() == QStringLiteral("generations")
            ? outputInfo.fileName()
            : QString();
}

QString manifestRelativePath(const QString& outputDir, const QString& filePath)
{
    return QDir(outputDir).relativeFilePath(QFileInfo(filePath).absoluteFilePath());
}

bool isSafeManifestRelativePath(const QString& path)
{
    if (path.trimmed().isEmpty() || QDir::isAbsolutePath(path))
        return false;
    const QStringList parts = QDir::fromNativeSeparators(path)
            .split(QLatin1Char('/'), Qt::SkipEmptyParts);
    return std::none_of(parts.constBegin(), parts.constEnd(), [](const QString& part) {
        return part == QStringLiteral("..");
    });
}

void sanitizeProjectArtifactMetadata(CompileArtifact& artifact,
                                     const QString& projectPath,
                                     const QString& outputDir,
                                     const QString& mainScriptFile,
                                     const QStringList& scriptFiles,
                                     const QString& generationId)
{
    QVariantMap metadata;
    metadata.insert(QStringLiteral("artifactScope"), QStringLiteral("project"));
    metadata.insert(QStringLiteral("generationId"), generationId);
    metadata.insert(QStringLiteral("artifactPath"), manifestRelativePath(outputDir, artifact.path));
    metadata.insert(QStringLiteral("sourceFile"),
                    DSLCompilerInternal::projectRelativePath(projectPath, mainScriptFile));
    metadata.insert(QStringLiteral("mainScriptFile"),
                    DSLCompilerInternal::projectRelativePath(projectPath, mainScriptFile));
    QStringList relativeScripts;
    for (const QString& script : scriptFiles)
        relativeScripts.append(DSLCompilerInternal::projectRelativePath(projectPath, script));
    metadata.insert(QStringLiteral("scriptFiles"), relativeScripts);
    artifact.metadata = metadata;
}

} // namespace

CompileResult DSLCompilerInterface::buildCompileResult(const QString& sourceFile,
                                                       const QString& outputDir,
                                                       const QString& projectName,
                                                       const QString& mainScriptFile,
                                                       const QStringList& scriptFiles,
                                                       bool success,
                                                       const QString& stdOut,
                                                       const QString& stdErr) const
{
    CompileResult result;
    result.success = success;
    result.projectName = projectName;
    result.stdOut = stdOut;
    result.stdErr = stdErr;

    if (!stdErr.trimmed().isEmpty() && !success) {
        result.errors = stdErr.split(QRegularExpression(QStringLiteral("[\r\n]+")),
                                     Qt::SkipEmptyParts);
    }

    const QString outputFile = DSLCompilerInternal::defaultOutputFileForSource(sourceFile, outputDir);
    if (QFileInfo::exists(outputFile)) {
        CompileArtifact artifact;
        artifact.type = QStringLiteral("download");
        artifact.path = outputFile;
        artifact.format = QStringLiteral("dsl_custom");
        artifact.checksum = DSLCompilerInternal::sha256ForFile(outputFile);
        artifact.metadata.insert(QStringLiteral("sourceFile"), sourceFile);
        artifact.metadata.insert(QStringLiteral("mainScriptFile"), mainScriptFile.isEmpty() ? sourceFile : mainScriptFile);
        artifact.metadata.insert(QStringLiteral("scriptFiles"), scriptFiles);
        artifact.metadata.insert(QStringLiteral("artifactScope"), QStringLiteral("project"));
        artifact.metadata.insert(QStringLiteral("outputDir"), outputDir);
        result.artifacts.append(artifact);
    }

    auto appendSidecarArtifact = [&](const QString& suffix,
                                     const QString& type,
                                     const QString& format) {
        const QString path = DSLCompilerInternal::outputSidecarFileForSource(sourceFile, outputDir, suffix);
        if (!QFileInfo::exists(path)) {
            return;
        }
        CompileArtifact artifact;
        artifact.type = type;
        artifact.path = path;
        artifact.format = format;
        artifact.checksum = DSLCompilerInternal::sha256ForFile(path);
        artifact.metadata.insert(QStringLiteral("sourceFile"), sourceFile);
        artifact.metadata.insert(QStringLiteral("mainScriptFile"), mainScriptFile.isEmpty() ? sourceFile : mainScriptFile);
        artifact.metadata.insert(QStringLiteral("scriptFiles"), scriptFiles);
        artifact.metadata.insert(QStringLiteral("artifactScope"), QStringLiteral("project"));
        artifact.metadata.insert(QStringLiteral("outputDir"), outputDir);
        result.artifacts.append(artifact);
    };

    appendSidecarArtifact(QStringLiteral(".list"),
                          QString::fromLatin1(CompileArtifactType::ParameterInitials),
                          QStringLiteral("lh_parameter_initials"));
    appendSidecarArtifact(QStringLiteral(".typ"),
                          QString::fromLatin1(CompileArtifactType::ParameterLayout),
                          QStringLiteral("lh_parameter_layout"));
    appendSidecarArtifact(QStringLiteral(".rep"),
                          QString::fromLatin1(CompileArtifactType::CompileReport),
                          QStringLiteral("lh_compile_report"));

    return result;
}

CompileResult DSLCompilerInterface::buildCompileResult(const QString& sourceFile,
                                                       const QString& outputDir,
                                                       const QString& projectName,
                                                       const QString& mainScriptFile,
                                                       const QStringList& scriptFiles,
                                                       bool success,
                                                       const QString& stdOut,
                                                       const QString& stdErr,
                                                       const ProjectRuntimeConfig& config) const
{
    return buildCompileResult(sourceFile,
                              outputDir,
                              projectName,
                              mainScriptFile,
                              scriptFiles,
                              success,
                              stdOut,
                              stdErr,
                              config,
                              QFileInfo(mainScriptFile).absolutePath(),
                              generationIdForDirectory(outputDir));
}

CompileResult DSLCompilerInterface::buildCompileResult(const QString& sourceFile,
                                                       const QString& outputDir,
                                                       const QString& projectName,
                                                       const QString& mainScriptFile,
                                                       const QStringList& scriptFiles,
                                                       bool success,
                                                       const QString& stdOut,
                                                       const QString& stdErr,
                                                       const ProjectRuntimeConfig& config,
                                                       const QString& projectPath,
                                                       const QString& generationId) const
{
    CompileResult result = buildCompileResult(sourceFile,
                                              outputDir,
                                              projectName,
                                              mainScriptFile,
                                              scriptFiles,
                                              success,
                                              stdOut,
                                              stdErr);
    result.generationId = generationId;
    result.metadata.insert(QStringLiteral("generationId"), generationId);
    result.metadata.insert(QStringLiteral("generationDirectory"),
                           DSLCompilerInternal::projectRelativePath(projectPath, outputDir));

    const QString profileSource = DSLCompilerInternal::profileSourcePath(projectPath, config);
    const QString profileSourceRelative =
            DSLCompilerInternal::projectRelativePath(projectPath, profileSource);
    if (!profileSourceRelative.isEmpty() && isSafeManifestRelativePath(profileSourceRelative)) {
        result.metadata.insert(QStringLiteral("downloadProfileSourcePath"), profileSourceRelative);
    }

    for (CompileArtifact& artifact : result.artifacts) {
        sanitizeProjectArtifactMetadata(artifact,
                                        projectPath,
                                        outputDir,
                                        mainScriptFile,
                                        scriptFiles,
                                        generationId);
    }

    if (!result.success)
        return result;

    const QString codePath = DSLCompilerInternal::projectOutputFile(outputDir);
    if (!QFileInfo::exists(codePath) || !QFileInfo(codePath).isFile()
            || DSLCompilerInternal::sha256ForFile(codePath).isEmpty()) {
        result.success = false;
        result.errors.append(QStringLiteral("generation 缺少有效 main.code，已阻止发布。"));
        return result;
    }

    const auto appendRequiredArtifact = [&](const QString& path,
                                            const QString& type,
                                            const QString& format,
                                            const QString& error) {
        if (!QFileInfo::exists(path) || !QFileInfo(path).isFile()) {
            result.success = false;
            result.errors.append(error);
            return;
        }
        CompileArtifact artifact;
        artifact.type = type;
        artifact.path = path;
        artifact.format = format;
        artifact.checksum = DSLCompilerInternal::sha256ForFile(path);
        if (artifact.checksum.isEmpty()) {
            result.success = false;
            result.errors.append(error + QStringLiteral("（无法计算 checksum）"));
            return;
        }
        sanitizeProjectArtifactMetadata(artifact,
                                        projectPath,
                                        outputDir,
                                        mainScriptFile,
                                        scriptFiles,
                                        generationId);
        result.artifacts.append(artifact);
    };

    appendRequiredArtifact(QDir(outputDir).filePath(QStringLiteral("download_profile.json")),
                           QStringLiteral("download_profile"),
                           QStringLiteral("json"),
                           QStringLiteral("generation 缺少 download_profile.json，已阻止发布。"));

    CompileArtifact pointsArtifact = generateRuntimePointsJson(outputDir, config);
    if (pointsArtifact.path.isEmpty()) {
        result.success = false;
        result.errors.append(QStringLiteral("无法生成 runtime_points.json，已阻止发布。"));
    } else {
        sanitizeProjectArtifactMetadata(pointsArtifact,
                                        projectPath,
                                        outputDir,
                                        mainScriptFile,
                                        scriptFiles,
                                        generationId);
        result.artifacts.append(pointsArtifact);
    }

    const auto points = RuntimePointConverter::fromProjectConfig(config);
    int parameterCount = 0;
    for (const auto& pt : points) {
        if (pt.kind == RuntimePointKind::Parameter)
            ++parameterCount;
    }

    if (!result.success)
        return result;

    CompileArtifact manifestArtifact = generateRuntimeManifestJson(
        outputDir,
        projectPath,
        projectName,
        mainScriptFile,
        scriptFiles,
        points.size(),
        parameterCount);
    if (manifestArtifact.path.isEmpty()) {
        result.success = false;
        result.errors.append(QStringLiteral("无法提交或校验 runtime_manifest.json，已阻止发布。"));
        return result;
    }
    sanitizeProjectArtifactMetadata(manifestArtifact,
                                    projectPath,
                                    outputDir,
                                    mainScriptFile,
                                    scriptFiles,
                                    generationId);
    result.artifacts.append(manifestArtifact);
    result.metadata.insert(QStringLiteral("runtimeManifestPath"),
                           DSLCompilerInternal::projectRelativePath(projectPath, manifestArtifact.path));
    result.metadata.insert(QStringLiteral("downloadProfilePath"),
                           DSLCompilerInternal::projectRelativePath(
                               projectPath,
                               QDir(outputDir).filePath(QStringLiteral("download_profile.json"))));
    result.metadata.insert(QStringLiteral("runtimePointsPath"),
                           DSLCompilerInternal::projectRelativePath(
                               projectPath,
                               QDir(outputDir).filePath(QStringLiteral("runtime_points.json"))));
    return result;
}

CompileArtifact DSLCompilerInterface::generateRuntimePointsJson(
    const QString& outputDir, const ProjectRuntimeConfig& config) const
{
    const auto points = RuntimePointConverter::fromProjectConfig(config);

    QJsonArray arr;
    for (const auto& pt : points) {
        QJsonObject obj;
        obj[QStringLiteral("id")] = pt.id;
        obj[QStringLiteral("name")] = pt.name;

        QString kindStr;
        switch (pt.kind) {
        case RuntimePointKind::Variable:  kindStr = QStringLiteral("Variable");  break;
        case RuntimePointKind::Parameter: kindStr = QStringLiteral("Parameter"); break;
        case RuntimePointKind::Status:    kindStr = QStringLiteral("Status");    break;
        case RuntimePointKind::Alarm:     kindStr = QStringLiteral("Alarm");     break;
        case RuntimePointKind::Resource:  kindStr = QStringLiteral("Resource");  break;
        }
        obj[QStringLiteral("kind")] = kindStr;
        obj[QStringLiteral("dataType")] = pt.dataType;
        obj[QStringLiteral("unit")] = pt.unit;

        QString accessStr;
        switch (pt.access) {
        case RuntimePointAccess::ReadOnly:  accessStr = QStringLiteral("ReadOnly");  break;
        case RuntimePointAccess::WriteOnly: accessStr = QStringLiteral("WriteOnly"); break;
        case RuntimePointAccess::ReadWrite: accessStr = QStringLiteral("ReadWrite"); break;
        }
        obj[QStringLiteral("access")] = accessStr;
        obj[QStringLiteral("sourceModule")] = pt.sourceModule;
        obj[QStringLiteral("bindingPath")] = pt.bindingPath;
        if (!pt.addressing.isEmpty())
            obj[QStringLiteral("addressing")] = QJsonObject::fromVariantMap(pt.addressing);
        if (!pt.defaultValue.isNull())
            obj[QStringLiteral("defaultValue")] = QJsonValue::fromVariant(pt.defaultValue);
        if (!pt.metadata.isEmpty())
            obj[QStringLiteral("metadata")] = QJsonObject::fromVariantMap(pt.metadata);

        arr.append(obj);
    }

    const QString filePath = QDir(outputDir).absoluteFilePath(
        QStringLiteral("runtime_points.json"));
    QSaveFile file(filePath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        qWarning() << "[DSLCompilerInterface] Failed to write" << filePath;
        return {};
    }
    const QByteArray json = QJsonDocument(arr).toJson(QJsonDocument::Indented);
    if (file.write(json) != json.size() || !file.commit()) {
        qWarning() << "[DSLCompilerInterface] Failed to commit" << filePath;
        return {};
    }

    CompileArtifact artifact;
    artifact.type = QString::fromLatin1(CompileArtifactType::RuntimePoints);
    artifact.path = filePath;
    artifact.format = QStringLiteral("json");
    artifact.checksum = DSLCompilerInternal::sha256ForFile(filePath);
    artifact.metadata.insert(QStringLiteral("pointCount"), arr.size());
    return artifact;
}

CompileArtifact DSLCompilerInterface::generateRuntimeManifestJson(
    const QString& outputDir,
    const QString& projectPath,
    const QString& projectName,
    const QString& mainScriptFile,
    const QStringList& scriptFiles,
    int pointCount,
    int parameterCount) const
{
    QJsonObject manifest;
    const QString generationId = generationIdForDirectory(outputDir);
    const QString codeFile = DSLCompilerInternal::projectOutputFile(outputDir);
    const QString profileFile = QDir(outputDir).filePath(QStringLiteral("download_profile.json"));
    const QString pointsFile = QDir(outputDir).filePath(QStringLiteral("runtime_points.json"));
    manifest[QStringLiteral("generationId")] = generationId;
    manifest[QStringLiteral("complete")] = false;
    manifest[QStringLiteral("projectName")] = projectName;
    manifest[QStringLiteral("mainScriptPath")] =
            DSLCompilerInternal::projectRelativePath(projectPath, mainScriptFile);
    manifest[QStringLiteral("dslScriptPath")] =
            DSLCompilerInternal::projectRelativePath(projectPath, mainScriptFile);

    QJsonArray scriptsArr;
    for (const auto& s : scriptFiles)
        scriptsArr.append(DSLCompilerInternal::projectRelativePath(projectPath, s));
    manifest[QStringLiteral("scriptFiles")] = scriptsArr;

    QJsonObject sourcePaths;
    sourcePaths[QStringLiteral("mainScriptPath")] =
            DSLCompilerInternal::projectRelativePath(projectPath, mainScriptFile);
    sourcePaths[QStringLiteral("dslScriptPath")] =
            DSLCompilerInternal::projectRelativePath(projectPath, mainScriptFile);
    manifest[QStringLiteral("sourcePaths")] = sourcePaths;
    manifest[QStringLiteral("sourceFileCount")] = scriptFiles.size();
    manifest[QStringLiteral("scriptFileCount")] = scriptFiles.size();

    QJsonArray artifactPathsArr;
    QJsonObject artifactChecksums;
    auto appendArtifact = [&](const QString& path) {
        if (!QFileInfo::exists(path))
            return;
        const QString relative = manifestRelativePath(outputDir, path);
        const QString checksum = DSLCompilerInternal::sha256ForFile(path);
        if (relative.isEmpty() || QDir::isAbsolutePath(relative) || hasParentTraversal(relative)
                || checksum.isEmpty()) {
            return;
        }
        artifactPathsArr.append(relative);
        artifactChecksums[relative] = checksum;
    };
    appendArtifact(codeFile);
    appendArtifact(profileFile);
    appendArtifact(pointsFile);
    const QString listPath = DSLCompilerInternal::outputSidecarFileForSource(
        mainScriptFile, outputDir, QStringLiteral(".list"));
    appendArtifact(listPath);
    const QString typPath = DSLCompilerInternal::outputSidecarFileForSource(
        mainScriptFile, outputDir, QStringLiteral(".typ"));
    appendArtifact(typPath);
    const QString reportPath = DSLCompilerInternal::outputSidecarFileForSource(
        mainScriptFile, outputDir, QStringLiteral(".rep"));
    appendArtifact(reportPath);
    const QString codeRelative = manifestRelativePath(outputDir, codeFile);
    const QString profileRelative = manifestRelativePath(outputDir, profileFile);
    const QString pointsRelative = manifestRelativePath(outputDir, pointsFile);
    const QString codeChecksum = DSLCompilerInternal::sha256ForFile(codeFile);
    const QString profileChecksum = DSLCompilerInternal::sha256ForFile(profileFile);
    const QString pointsChecksum = DSLCompilerInternal::sha256ForFile(pointsFile);
    if (!artifactPathsArr.contains(QJsonValue(codeRelative))
            || !artifactPathsArr.contains(QJsonValue(profileRelative))
            || !artifactPathsArr.contains(QJsonValue(pointsRelative))
            || codeChecksum.isEmpty() || profileChecksum.isEmpty() || pointsChecksum.isEmpty()) {
        return {};
    }
    manifest[QStringLiteral("artifactPaths")] = artifactPathsArr;
    manifest[QStringLiteral("artifactChecksums")] = artifactChecksums;
    manifest[QStringLiteral("codePath")] = codeRelative;
    manifest[QStringLiteral("codeChecksum")] = codeChecksum;
    manifest[QStringLiteral("runtimePointsPath")] = pointsRelative;
    manifest[QStringLiteral("runtimePointsChecksum")] = pointsChecksum;
    manifest[QStringLiteral("downloadProfilePath")] = profileRelative;
    manifest[QStringLiteral("downloadProfileChecksum")] = profileChecksum;
    manifest[QStringLiteral("runtimeManifestPath")] = QStringLiteral("runtime_manifest.json");

    manifest[QStringLiteral("generatedAt")] = QDateTime::currentDateTime().toString(Qt::ISODate);
    manifest[QStringLiteral("pointCount")] = pointCount;
    manifest[QStringLiteral("parameterCount")] = parameterCount;

    manifest[QStringLiteral("complete")] = true;

    const QString filePath = QDir(outputDir).absoluteFilePath(
        QStringLiteral("runtime_manifest.json"));
    QSaveFile file(filePath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        qWarning() << "[DSLCompilerInterface] Failed to write" << filePath;
        return {};
    }
    const QByteArray json = QJsonDocument(manifest).toJson(QJsonDocument::Indented);
    if (file.write(json) != json.size() || !file.commit()) {
        qWarning() << "[DSLCompilerInterface] Failed to commit" << filePath;
        return {};
    }

    QFile verify(filePath);
    if (!verify.open(QIODevice::ReadOnly | QIODevice::Text))
        return {};
    QJsonParseError parseError;
    const QJsonDocument committed = QJsonDocument::fromJson(verify.readAll(), &parseError);
    if (parseError.error != QJsonParseError::NoError || !committed.isObject()
            || !committed.object().value(QStringLiteral("complete")).toBool(false)
            || committed.object().value(QStringLiteral("generationId")).toString() != generationId)
        return {};
    const QJsonObject committedObject = committed.object();
    const QStringList mandatoryManifestPaths = {
        QStringLiteral("codePath"),
        QStringLiteral("downloadProfilePath"),
        QStringLiteral("runtimePointsPath")
    };
    for (const QString& key : mandatoryManifestPaths) {
        if (!isSafeManifestRelativePath(committedObject.value(key).toString()))
            return {};
    }
    const QJsonArray committedArtifacts = committedObject.value(QStringLiteral("artifactPaths")).toArray();
    if (committedArtifacts.isEmpty())
        return {};
    for (const QJsonValue& value : committedArtifacts) {
        if (!isSafeManifestRelativePath(value.toString()))
            return {};
    }
    const QStringList sourcePathKeys = {
        QStringLiteral("mainScriptPath"), QStringLiteral("dslScriptPath")
    };
    for (const QString& key : sourcePathKeys) {
        if (!isSafeManifestRelativePath(committedObject.value(key).toString()))
            return {};
    }
    const QJsonArray committedScripts = committedObject.value(QStringLiteral("scriptFiles")).toArray();
    for (const QJsonValue& value : committedScripts) {
        if (!isSafeManifestRelativePath(value.toString()))
            return {};
    }

    CompileArtifact artifact;
    artifact.type = QString::fromLatin1(CompileArtifactType::RuntimeManifest);
    artifact.path = filePath;
    artifact.format = QStringLiteral("json");
    artifact.checksum = DSLCompilerInternal::sha256ForFile(filePath);
    return artifact;
}
