#include "DSLCompilerInterface.h"
#include "DSLCompilerInternal.h"

#include <QCryptographicHash>
#include <QDateTime>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QProcess>
#include <QRegularExpression>
#include <QDebug>
#include "TextEncoding.h"

namespace DSLCompilerInternal {

QString defaultOutputFileForSource(const QString& sourceFile, const QString& outputDir)
{
    const QFileInfo sourceInfo(sourceFile);
    QDir dir(outputDir);
    return dir.absoluteFilePath(sourceInfo.completeBaseName() + QStringLiteral(".code"));
}

QString outputSidecarFileForSource(const QString& sourceFile,
                                   const QString& outputDir,
                                   const QString& suffix)
{
    const QFileInfo sourceInfo(sourceFile);
    QDir dir(outputDir);
    return dir.absoluteFilePath(sourceInfo.completeBaseName() + suffix);
}

QStringList buildCompilerProcessArgs(const QString& entryScript,
                                     const QString& compilerInputFile,
                                     const QString& outputFile)
{
    return QStringList()
            << entryScript
            << QDir::toNativeSeparators(compilerInputFile)
            << QStringLiteral("-o")
            << QDir::toNativeSeparators(outputFile)
            << QStringLiteral("-v");
}

bool prependCodeMetadataHeader(const QString& outputFile,
                               const QString& sourceFile,
                               const QString& projectName,
                               const QString& compilerInputFile,
                               QString* errorMessage)
{
    QFile file(outputFile);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        if (errorMessage) {
            *errorMessage = QStringLiteral("Failed to read generated .code file: %1").arg(outputFile);
        }
        return false;
    }
    const QByteArray body = file.readAll();
    file.close();

    const QFileInfo sourceInfo(sourceFile);
    const QFileInfo outputInfo(outputFile);
    const QFileInfo compilerInputInfo(compilerInputFile);
    QStringList header;
    header << QStringLiteral("// Generated by LH compiler integration")
           << QStringLiteral("// GeneratedAt: %1").arg(QDateTime::currentDateTime().toString(Qt::ISODate))
           << QStringLiteral("// Project: %1").arg(projectName.isEmpty() ? QStringLiteral("-") : projectName)
           << QStringLiteral("// Source: %1").arg(QDir::toNativeSeparators(sourceInfo.absoluteFilePath()))
           << QStringLiteral("// CompilerInput: %1").arg(QDir::toNativeSeparators(compilerInputInfo.absoluteFilePath()))
           << QStringLiteral("// Output: %1").arg(QDir::toNativeSeparators(outputInfo.absoluteFilePath()))
           << QStringLiteral("// Format: .lh -> .code")
           << QString();

    if (!file.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate)) {
        if (errorMessage) {
            *errorMessage = QStringLiteral("Failed to write generated .code metadata header: %1").arg(outputFile);
        }
        return false;
    }
    file.write(header.join(QLatin1Char('\n')).toUtf8());
    file.write(body);
    return true;
}

QString sha256ForFile(const QString& filePath)
{
    QFile file(filePath);
    if (!file.open(QIODevice::ReadOnly)) {
        return QString();
    }
    QCryptographicHash hash(QCryptographicHash::Sha256);
    hash.addData(&file);
    return QString::fromLatin1(hash.result().toHex());
}

QString runDslCompilerProcess(const QString& python,
                              const QString& entryScript,
                              const QString& compilerInputFile,
                              const QString& outputFile,
                              const QString& workDir,
                              QString* compilerStdout,
                              QString* compilerStderr)
{
    const QStringList args = buildCompilerProcessArgs(entryScript, compilerInputFile, outputFile);

    QProcess proc;
    proc.setProgram(python);
    proc.setArguments(args);
    proc.setWorkingDirectory(workDir);

    qInfo() << "[DSLCompilerInterface] Running:" << python << args
            << "cwd =" << workDir;

    proc.start();
    if (!proc.waitForFinished(120 * 1000)) {
        proc.kill();
        if (compilerStderr) {
            *compilerStderr = QStringLiteral("DSL compile process timeout.");
        }
        qWarning() << "[DSLCompilerInterface] compile process timeout.";
        return QStringLiteral("timeout");
    }

    const QString stdOut =
            TextEncoding::decodeUtf8WithLocalFallback(proc.readAllStandardOutput());
    const QString stdErr =
            TextEncoding::decodeUtf8WithLocalFallback(proc.readAllStandardError());

    if (compilerStdout) {
        *compilerStdout = stdOut;
    }
    if (compilerStderr) {
        *compilerStderr = stdErr;
    }

    if (proc.exitStatus() == QProcess::NormalExit
            && proc.exitCode() == 0
            && QFileInfo::exists(outputFile)) {
        return QString();
    }

    return QStringLiteral("exitCode=%1 outputFile=%2")
            .arg(proc.exitCode())
            .arg(outputFile);
}

} // namespace DSLCompilerInternal

CompileResult DSLCompilerInterface::buildCompileResult(const QString& sourceFile,
                                                       const QString& outputDir,
                                                       const QString& projectName,
                                                       const QString& mainScriptFile,
                                                       const QStringList& scriptFiles,
                                                       bool success,
                                                       const QString& stdOut,
                                                       const QString& stdErr) const
{
    CompileResult result;
    result.success = success;
    result.projectName = projectName;
    result.stdOut = stdOut;
    result.stdErr = stdErr;

    if (!stdErr.trimmed().isEmpty() && !success) {
        result.errors = stdErr.split(QRegularExpression(QStringLiteral("[\r\n]+")),
                                     Qt::SkipEmptyParts);
    }

    const QString outputFile = DSLCompilerInternal::defaultOutputFileForSource(sourceFile, outputDir);
    if (QFileInfo::exists(outputFile)) {
        CompileArtifact artifact;
        artifact.type = QStringLiteral("download");
        artifact.path = outputFile;
        artifact.format = QStringLiteral("dsl_custom");
        artifact.checksum = DSLCompilerInternal::sha256ForFile(outputFile);
        artifact.metadata.insert(QStringLiteral("sourceFile"), sourceFile);
        artifact.metadata.insert(QStringLiteral("mainScriptFile"), mainScriptFile.isEmpty() ? sourceFile : mainScriptFile);
        artifact.metadata.insert(QStringLiteral("scriptFiles"), scriptFiles);
        artifact.metadata.insert(QStringLiteral("artifactScope"), QStringLiteral("project"));
        artifact.metadata.insert(QStringLiteral("outputDir"), outputDir);
        result.artifacts.append(artifact);
    }

    auto appendSidecarArtifact = [&](const QString& suffix,
                                     const QString& type,
                                     const QString& format) {
        const QString path = DSLCompilerInternal::outputSidecarFileForSource(sourceFile, outputDir, suffix);
        if (!QFileInfo::exists(path)) {
            return;
        }
        CompileArtifact artifact;
        artifact.type = type;
        artifact.path = path;
        artifact.format = format;
        artifact.checksum = DSLCompilerInternal::sha256ForFile(path);
        artifact.metadata.insert(QStringLiteral("sourceFile"), sourceFile);
        artifact.metadata.insert(QStringLiteral("mainScriptFile"), mainScriptFile.isEmpty() ? sourceFile : mainScriptFile);
        artifact.metadata.insert(QStringLiteral("scriptFiles"), scriptFiles);
        artifact.metadata.insert(QStringLiteral("artifactScope"), QStringLiteral("project"));
        artifact.metadata.insert(QStringLiteral("outputDir"), outputDir);
        result.artifacts.append(artifact);
    };

    appendSidecarArtifact(QStringLiteral(".list"),
                          QString::fromLatin1(CompileArtifactType::ParameterInitials),
                          QStringLiteral("lh_parameter_initials"));
    appendSidecarArtifact(QStringLiteral(".typ"),
                          QString::fromLatin1(CompileArtifactType::ParameterLayout),
                          QStringLiteral("lh_parameter_layout"));
    appendSidecarArtifact(QStringLiteral(".rep"),
                          QString::fromLatin1(CompileArtifactType::CompileReport),
                          QStringLiteral("lh_compile_report"));

    return result;
}

CompileResult DSLCompilerInterface::buildCompileResult(const QString& sourceFile,
                                                       const QString& outputDir,
                                                       const QString& projectName,
                                                       const QString& mainScriptFile,
                                                       const QStringList& scriptFiles,
                                                       bool success,
                                                       const QString& stdOut,
                                                       const QString& stdErr,
                                                       const ProjectRuntimeConfig& config) const
{
    CompileResult result = buildCompileResult(sourceFile, outputDir, projectName,
                                              mainScriptFile, scriptFiles,
                                              success, stdOut, stdErr);

    if (result.success) {
        CompileArtifact pointsArtifact = generateRuntimePointsJson(outputDir, config);
        if (!pointsArtifact.path.isEmpty())
            result.artifacts.append(pointsArtifact);

        const auto points = RuntimePointConverter::fromProjectConfig(config);
        int parameterCount = 0;
        for (const auto& pt : points) {
            if (pt.kind == RuntimePointKind::Parameter)
                parameterCount++;
        }

        CompileArtifact manifestArtifact = generateRuntimeManifestJson(
            outputDir, projectName, mainScriptFile, scriptFiles,
            points.size(), parameterCount);
        if (!manifestArtifact.path.isEmpty())
            result.artifacts.append(manifestArtifact);
    }

    return result;
}

CompileArtifact DSLCompilerInterface::generateRuntimePointsJson(
    const QString& outputDir, const ProjectRuntimeConfig& config) const
{
    const auto points = RuntimePointConverter::fromProjectConfig(config);

    QJsonArray arr;
    for (const auto& pt : points) {
        QJsonObject obj;
        obj[QStringLiteral("id")] = pt.id;
        obj[QStringLiteral("name")] = pt.name;

        QString kindStr;
        switch (pt.kind) {
        case RuntimePointKind::Variable:  kindStr = QStringLiteral("Variable");  break;
        case RuntimePointKind::Parameter: kindStr = QStringLiteral("Parameter"); break;
        case RuntimePointKind::Status:    kindStr = QStringLiteral("Status");    break;
        case RuntimePointKind::Alarm:     kindStr = QStringLiteral("Alarm");     break;
        case RuntimePointKind::Resource:  kindStr = QStringLiteral("Resource");  break;
        }
        obj[QStringLiteral("kind")] = kindStr;
        obj[QStringLiteral("dataType")] = pt.dataType;
        obj[QStringLiteral("unit")] = pt.unit;

        QString accessStr;
        switch (pt.access) {
        case RuntimePointAccess::ReadOnly:  accessStr = QStringLiteral("ReadOnly");  break;
        case RuntimePointAccess::WriteOnly: accessStr = QStringLiteral("WriteOnly"); break;
        case RuntimePointAccess::ReadWrite: accessStr = QStringLiteral("ReadWrite"); break;
        }
        obj[QStringLiteral("access")] = accessStr;
        obj[QStringLiteral("sourceModule")] = pt.sourceModule;
        obj[QStringLiteral("bindingPath")] = pt.bindingPath;
        if (!pt.addressing.isEmpty())
            obj[QStringLiteral("addressing")] = QJsonObject::fromVariantMap(pt.addressing);
        if (!pt.defaultValue.isNull())
            obj[QStringLiteral("defaultValue")] = QJsonValue::fromVariant(pt.defaultValue);
        if (!pt.metadata.isEmpty())
            obj[QStringLiteral("metadata")] = QJsonObject::fromVariantMap(pt.metadata);

        arr.append(obj);
    }

    const QString filePath = QDir(outputDir).absoluteFilePath(
        QStringLiteral("runtime_points.json"));
    QFile file(filePath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate)) {
        qWarning() << "[DSLCompilerInterface] Failed to write" << filePath;
        return {};
    }
    file.write(QJsonDocument(arr).toJson(QJsonDocument::Indented));
    file.close();

    CompileArtifact artifact;
    artifact.type = QString::fromLatin1(CompileArtifactType::RuntimePoints);
    artifact.path = filePath;
    artifact.format = QStringLiteral("json");
    artifact.checksum = DSLCompilerInternal::sha256ForFile(filePath);
    artifact.metadata.insert(QStringLiteral("pointCount"), arr.size());
    return artifact;
}

CompileArtifact DSLCompilerInterface::generateRuntimeManifestJson(
    const QString& outputDir,
    const QString& projectName,
    const QString& mainScriptFile,
    const QStringList& scriptFiles,
    int pointCount,
    int parameterCount) const
{
    QJsonObject manifest;
    manifest[QStringLiteral("projectName")] = projectName;
    manifest[QStringLiteral("mainScriptPath")] = mainScriptFile;

    QJsonArray scriptsArr;
    for (const auto& s : scriptFiles)
        scriptsArr.append(s);
    manifest[QStringLiteral("scriptFiles")] = scriptsArr;

    QJsonArray artifactPathsArr;
    const QString codeFile = DSLCompilerInternal::defaultOutputFileForSource(mainScriptFile, outputDir);
    if (QFileInfo::exists(codeFile))
        artifactPathsArr.append(codeFile);
    const QString listPath = DSLCompilerInternal::outputSidecarFileForSource(
        mainScriptFile, outputDir, QStringLiteral(".list"));
    if (QFileInfo::exists(listPath))
        artifactPathsArr.append(listPath);
    const QString typPath = DSLCompilerInternal::outputSidecarFileForSource(
        mainScriptFile, outputDir, QStringLiteral(".typ"));
    if (QFileInfo::exists(typPath))
        artifactPathsArr.append(typPath);
    const QString reportPath = DSLCompilerInternal::outputSidecarFileForSource(
        mainScriptFile, outputDir, QStringLiteral(".rep"));
    if (QFileInfo::exists(reportPath))
        artifactPathsArr.append(reportPath);
    const QString pointsPath = QDir(outputDir).absoluteFilePath(
        QStringLiteral("runtime_points.json"));
    if (QFileInfo::exists(pointsPath))
        artifactPathsArr.append(pointsPath);
    manifest[QStringLiteral("artifactPaths")] = artifactPathsArr;

    manifest[QStringLiteral("generatedAt")] = QDateTime::currentDateTime().toString(Qt::ISODate);
    manifest[QStringLiteral("pointCount")] = pointCount;
    manifest[QStringLiteral("parameterCount")] = parameterCount;

    const QString filePath = QDir(outputDir).absoluteFilePath(
        QStringLiteral("runtime_manifest.json"));
    QFile file(filePath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate)) {
        qWarning() << "[DSLCompilerInterface] Failed to write" << filePath;
        return {};
    }
    file.write(QJsonDocument(manifest).toJson(QJsonDocument::Indented));
    file.close();

    CompileArtifact artifact;
    artifact.type = QString::fromLatin1(CompileArtifactType::RuntimeManifest);
    artifact.path = filePath;
    artifact.format = QStringLiteral("json");
    artifact.checksum = DSLCompilerInternal::sha256ForFile(filePath);
    return artifact;
}
